import requests

url = 'http://127.0.0.1:5000/data'

headers = {'content-type': 'application/json'}

testObject = {
    "username": "TestUser112",
    "age": 11,
    "gender":"female",
	"location": { 
        'country': "Spain",
        'city': "Madrid"
    },
    "diagnosis":"positive",
    "symptoms": {        
        'dry cough': True,
        'fever': True,
        'tiredness': False,
        'loss of taste or smell':False,
        'headache': True,
        'difficulty breathing or shortness of breath': True,
        'chest pain or pressure': False,
        'others': "Nothing"
    },
            
            
            
            
	"audio_features": {
        "chroma_10_mean": "0.0023706054937684",
        "chroma_10_std": "0.0",
        "chroma_11_mean": "0.0",
        "chroma_11_std": "0.0",
        "chroma_12_mean": "0.0",
        "chroma_12_std": "0.0",
        "chroma_1_mean": "0.0",
        "chroma_1_std": "0.0",
        "chroma_2_mean": "0.0",
        "chroma_2_std": "0.0",
        "chroma_3_mean": "0.0",
        "chroma_3_std": "0.0",
        "chroma_4_mean": "0.0",
        "chroma_4_std": "0.0",
        "chroma_5_mean": "0.0",
        "chroma_5_std": "0.0",
        "chroma_6_mean": "0.0",
        "chroma_6_std": "0.0",
        "chroma_7_mean": "0.0",
        "chroma_7_std": "0.0",
        "chroma_8_mean": "0.0",
        "chroma_8_std": "0.0",
        "chroma_9_mean": "0.0",
        "chroma_9_std": "0.0",
        "chroma_std_mean": "0.0",
        "chroma_std_std": "0.0",
        "delta chroma_10_mean": "0.0",
        "delta chroma_10_std": "0.0",
        "delta chroma_11_mean": "0.0",
        "delta chroma_11_std": "0.0",
        "delta chroma_12_mean": "0.0",
        "delta chroma_12_std":"0.0",
        "delta chroma_1_mean": "0.0",
        "delta chroma_1_std": "0.0",
        "delta chroma_2_mean": "0.0",
        "delta chroma_2_std": "0.0",
        "delta chroma_3_mean": "-2.1391572321258987e-05",
        "delta chroma_3_std": "0.0",
        "delta chroma_4_mean": "0.0",
        "delta chroma_4_std": "0.0",
        "delta chroma_5_mean": "0.0",
        "delta chroma_5_std": "0.0",
        "delta chroma_6_mean": "0.0",
        "delta chroma_6_std": "0.0",
        "delta chroma_7_mean": "0.0",
        "delta chroma_7_std": "0.0",
        "delta chroma_8_mean": "0.0",
        "delta chroma_8_std": "0.0",
        "delta chroma_9_mean": "0.0",
        "delta chroma_9_std": "0.0",
        "delta chroma_std_mean": "0.0",
        "delta chroma_std_std": "0.0",
        "delta energy_entropy_mean": "0.0",
        "delta energy_entropy_std": "0.0",
        "delta energy_mean": "0.0",
        "delta energy_std": "0.0",
        "delta mfcc_10_mean": "0.0",
        "delta mfcc_10_std": "0.0",
        "delta mfcc_11_mean": "0.0",
        "delta mfcc_11_std": "0.0",
        "delta mfcc_12_mean": "0.0",
        "delta mfcc_12_std": "0.0",
        "delta mfcc_13_mean": "0.0",
        "delta mfcc_13_std": "0.0",
        "delta mfcc_1_mean": "0.0",
        "delta mfcc_1_std": "0.0",
        "delta mfcc_2_mean": "0.0",
        "delta mfcc_2_std": "0.0",
        "delta mfcc_3_mean": "0.0",
        "delta mfcc_3_std": "0.0",
        "delta mfcc_4_mean": "0.0",
        "delta mfcc_4_std": "0.0",
        "delta mfcc_5_mean": "0.0",
        "delta mfcc_5_std": "0.0",
        "delta mfcc_6_mean": "0.0",
        "delta mfcc_6_std": "0.0",
        "delta mfcc_7_mean": "0.0",
        "delta mfcc_7_std": "0.0",
        "delta mfcc_8_mean": "0.0",
        "delta mfcc_8_std": "0.0",
        "delta mfcc_9_mean": "0.0",
        "delta mfcc_9_std": "0.0",
        "delta spectral_centroid_mean": "0.0",
        "delta spectral_centroid_std": "0.0",
        "delta spectral_entropy_mean": "0.0",
        "delta spectral_entropy_std": "0.0",
        "delta spectral_flux_mean": "0.0",
        "delta spectral_flux_std": "0.0",
        "delta spectral_rolloff_mean": "0.0",
        "delta spectral_rolloff_std": "0.0",
        "delta spectral_spread_mean": "0.0",
        "delta spectral_spread_std": "0.0",
        "delta zcr_mean": "0.0",
        "delta zcr_std": "0.0",
        "energy_entropy_mean": "0.0",
        "energy_entropy_std": "0.0",
        "energy_mean": "0.0",
        "energy_std": "0.0",
        "label": "1",
        "mfcc_10_mean": "0.0",
        "mfcc_10_std": "0.0",
        "mfcc_11_mean": "0.0",
        "mfcc_11_std": "0.0",
        "mfcc_12_mean": "0.0",
        "mfcc_12_std": "0.0",
        "mfcc_13_mean": "0.0",
        "mfcc_13_std": "0.0",
        "mfcc_1_mean": "0.0",
        "mfcc_1_std": "0.0",
        "mfcc_2_mean": "0.0",
        "mfcc_2_std": "0.0",
        "mfcc_3_mean": "0.0",
        "mfcc_3_std": "0.0",
        "mfcc_4_mean": "0.0",
        "mfcc_4_std": "0.0",
        "mfcc_5_mean": "0.0",
        "mfcc_5_std": "0.0",
        "mfcc_6_mean": "0.0",
        "mfcc_6_std": "0.0",
        "mfcc_7_mean": "0.0",
        "mfcc_7_std": "0.0",
        "mfcc_8_mean": "0.0",
        "mfcc_8_std": "0.0",
        "mfcc_9_mean": "0.0",
        "mfcc_9_std": "0.0",
        "spectral_centroid_mean": "0.0",
        "spectral_centroid_std": "0.0",
        "spectral_entropy_mean": "0.0",
        "spectral_entropy_std": "0.0",
        "spectral_flux_mean": "0.0",
        "spectral_flux_std": "0.0",
        "spectral_rolloff_mean": "0.0",
        "spectral_rolloff_std": "0.0",
        "spectral_spread_mean": "0.0",
        "spectral_spread_std": "0.0",
        "zcr_mean": "0.0",
        "zcr_std": "0.0",
    },
    #"audio_file": None
} 


x = requests.post(url, json=testObject, headers=headers)
print(x.json())